In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('advertising.csv')

In [3]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

### Using sklearn LinearRegression

In [6]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [7]:
lr.fit(x_train,y_train)
print(lr.intercept_)
print(lr.coef_)

4.773205203269834
[ 0.05368006  0.11152624 -0.00351166]


In [8]:
from sklearn.metrics import r2_score

In [9]:
y_pred=lr.predict(x_test)
r2_score(y_test,y_pred)

0.8645053923967725

In [10]:
y_pred

array([10.70988945,  8.68629773,  9.5778695 , 24.86207988, 14.65584473,
        8.3214275 , 10.43048002, 18.4453765 ,  9.73394291, 17.9290798 ,
       23.369886  , 10.67916356, 13.44032325, 17.17416235, 11.77380187,
       13.37072678, 21.26009906,  9.19666875, 14.13201846, 18.9260716 ,
       24.75507991, 12.48481182, 16.57130583, 13.77344772,  7.79299106,
       15.19648316, 14.71607944, 20.73862119, 17.01041859,  8.83474391,
       12.09424377, 20.74886454, 21.26147987, 21.90420095,  7.08087067,
        7.04431681,  9.15949871, 15.47796148, 13.28282334,  7.23769883])

### Using Batch Gradient Descent coded from scratch

In [11]:
class GDRegressor:
    def __init__(self,learning_rate=0.001,epochs=100):
        self.intercept_=None
        self.coef_= None
        self.lr = learning_rate
        self.epoch = epochs

    def fit(self,X,Y):
        self.intercept_=120
        self.coef_=np.ones(X.shape[1])

        for i in range(self.epoch):
            # updating intercept
            y_hat=self.intercept_ + np.dot(X,self.coef_)
            intercept_der=-2 * np.mean(Y-y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)

            # updating coefficients
            coef_der = -(2/X.shape[0]) * (np.dot(Y-y_hat,X))
            self.coef_ =self.coef_ - (self.lr * coef_der)

    def predict(self,X):
        return np.dot(X,self.coef_)+self.intercept_

In [12]:
myGD=GDRegressor(learning_rate=0.01,epochs=10000)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [14]:
myGD.fit(x_train,y_train)

In [15]:
myGD.intercept_

np.float64(15.355625000000042)

In [16]:
myGD.coef_

array([ 4.54624242,  1.6383335 , -0.07507122])

In [17]:
y_pred2=myGD.predict(x_test)


In [18]:
r2_score(y_test,y_pred2)

0.8645053923967719