In [1]:
import numpy as np

### Creating array from list

In [2]:
arr_1d=np.array([1,2,3,4,5])
print("1D array:",arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [ ]:
py_list=[1,2,3]
print("Python list multiplication ",py_list*2)

np_array=np.array([1,2,4])
print("Numpy array multiplication : ",np_array*2)



Python list multiplication  [1, 2, 3, 1, 2, 3]
Numpy array multiplication :  [2 4 8]


### Creating array from scratch


In [ ]:
zeros=np.zeros((3,4))
print("Zeros array: \n",zeros)

ones=np.ones((2,3))
print("Ones array:\n",ones)

full=np.full((3,3),6)
print("Full array: \n",full)

sequence=np.arange(2,20,2)
print("Sequence array: ",sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
[ 2  4  6  8 10 12 14 16 18]


### Array properties


In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Size: ",arr.size)
print("Data type: ",arr.dtype)

Shape:  (3, 3)
Dimension:  2
Size:  9
Data type:  int64


### Array reshaping

In [25]:
arr=np.arange(12)
print("Original array:",arr)

reshaped=arr.reshape((3,4))
print("\nReshaped array:",reshaped)

flatten=reshaped.flatten()
print("\nFlattened array: ",flatten)

raveled=reshaped.ravel()
print("\nRaveled array:",raveled)

transpose=reshaped.T
print("\nTranspose:",transpose)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
