In [3]:
import numpy as np
print(np.__version__)

2.2.6


### Array indexing and slicing

In [4]:
arr=np.arange(1,11)
print("Basic Slicing: ",arr[2:7])
print("With Step: ",arr[1:8:2])
print("Negative indexing:",arr[-2])

Basic Slicing:  [3 4 5 6 7]
With Step:  [2 4 6 8]
Negative indexing: 9


In [5]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element: ",arr_2d[1,2])
print("Entire row: ",arr_2d[1])
print("Entire column: ",arr_2d[:,1])

Specific element:  6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting

In [6]:
unsorted=np.array([3,6,1,4,2,5,9,8,7])
print("Sorted Array: ",np.sort(unsorted))

unsorted_2d=np.array([[3,1],
                      [1,2],
                      [2,3]])
print("2D array sorted by column: ",np.sort(unsorted_2d,axis=0))
print("2D array sorted by row: ",np.sort(unsorted_2d,axis=1))

Sorted Array:  [1 2 3 4 5 6 7 8 9]
2D array sorted by column:  [[1 1]
 [2 2]
 [3 3]]
2D array sorted by row:  [[1 3]
 [1 2]
 [2 3]]


### Filter

In [7]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers % 2 == 0]
print("Even numbers:",even_number)

#Filter with mask
mask=numbers>5
print("Numbers greater than 5:",numbers[mask])

Even numbers: [ 2  4  6  8 10]
Numbers greater than 5: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [8]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print("Np.where(): ",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np.where():  [ 6  7  8  9 10]


In [9]:
condition_array=np.where(numbers>5,numbers*2,0)
print(condition_array)

[ 0  0  0  0  0 12 14 16 18 20]


### Adding and removing data

In [10]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


In [17]:
original=np.array([[1,2],[3,4]])
new_row=np.array([5,6])
with_new_row=np.vstack((original,new_row))
print(original)
print('\n',with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print('\n',with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]


In [19]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
print("Array after deletion:",deleted)

Array after deletion: [1 2 4 5]


### Array Compatibility

In [11]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11])

print("Compatibility of a and b : ",a.shape==b.shape)
print("Compatibility of a and c : ",a.shape==c.shape)

Compatibility of a and b :  True
Compatibility of a and c :  False
