# 🧮 NumPy Practice Set (Easy → Hard + Dataset Challenge)
This notebook is designed to help you master **NumPy** step-by-step — from basic array manipulation to real-world dataset challenges.

**Instructions:**
- Attempt each section in order.
- Write your answers in the provided code cells.
- Use `Shift + Enter` to run cells.
- Don't import any libraries other than `numpy` unless instructed.

Let's get started 🚀

In [2]:
import numpy as np

# Check version
print('NumPy Version:', np.__version__)

NumPy Version: 2.2.6


## 🟢 Easy Level (Basics & Array Manipulation)

1. Create a NumPy array of integers from 1 to 20.  
2. Generate a 3x3 matrix with values ranging from 2 to 10.  
3. Create a 5x5 array of all `True` values.  
4. Convert a Python list `[1, 2, 3, 4, 5]` into a NumPy array and multiply each element by 3.  
5. Create an array of zeros of size 10 and replace the fifth element with 5.  
6. Create an array of 10 random integers between 1 and 100 and find the maximum and minimum values.  
7. Create an array from 0 to 9 and reverse it without using slicing.  
8. Reshape an array of 1 to 9 into a 3x3 matrix.  
9. Create an identity matrix of size 4x4.  
10. Create two arrays and perform element-wise addition, subtraction, multiplication, and division.


In [3]:
# Create a NumPy array of integers from 1 to 20
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
# Generate a 3x3 matrix with values ranging from 2 to 10
matrix=np.arange(2,11).reshape((3,3))
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
# Generate a 5x5 array of all True values
arr2=np.full((5,5),True)
arr2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
# Convert a Python list [1, 2, 3, 4, 5] into a NumPy array and multiply each element by 3.
L=[1,2,3,4,5]
np_arr=np.array(L)*3
print(np_arr)

[ 3  6  9 12 15]


In [7]:
# Create an array of zeros of size 10 and replace the fifth element with 5.
zeros=np.zeros(10)
zeros[4]=5
print(zeros)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


In [8]:
# Create an array of 10 random integers between 1 and 100 and find the maximum and minimum values.
random_arr=np.random.randint(1,100,10)
max=np.max(random_arr)
min=np.min(random_arr)
print(random_arr)
print("Maximum:",max)
print("Minimum:",min)

[15 21 12 31  4 30 90 39 57 85]
Maximum: 90
Minimum: 4


In [9]:
# Create an array from 0 to 9 and reverse it without using slicing
arr3=np.arange(0,10)
rev_arr=np.flip(arr3)
print("Original Array :",arr3)
print("Reversed Array :",rev_arr)

Original Array : [0 1 2 3 4 5 6 7 8 9]
Reversed Array : [9 8 7 6 5 4 3 2 1 0]


In [10]:
# Reshape an array of 1 to 9 into a 3x3 matrix.
arr4=np.arange(1,10)
reshaped=arr4.reshape((3,3))
print("Reshaped array :\n",reshaped)

Reshaped array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Create an identity matrix of size 4x4.
identity=np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Create two arrays and perform element-wise addition, subtraction, multiplication, and division.
arr1=np.arange(1,6)
arr2=np.arange(6,11)
add_arr=arr1+arr2
sub_arr=arr1-arr2
mult_arr=arr1*arr2
div_arr=arr1/arr2
print("Array 1 :",arr1)
print("Array 2 :",arr2)
print("Addition :\n",add_arr)
print("Subtraction :\n",sub_arr)
print("Multiplication :\n",mult_arr)
print("Division :\n",div_arr)

Array 1 : [1 2 3 4 5]
Array 2 : [ 6  7  8  9 10]
Addition :
 [ 7  9 11 13 15]
Subtraction :
 [-5 -5 -5 -5 -5]
Multiplication :
 [ 6 14 24 36 50]
Division :
 [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## 🟡 Intermediate Level (Indexing, Math Ops, Broadcasting, Aggregations)

1. Create a 4x4 array and extract the diagonal elements.  
2. Given a 1D array `[1, 2, 3, 4, 5, 6, 7, 8, 9]`, extract all even numbers.  
3. Replace all odd numbers in an array with `-1`.  
4. Normalize a random 3x3 matrix (values scaled between 0 and 1).  
5. Stack two arrays vertically and horizontally using `np.vstack()` and `np.hstack()`.  
6. Compute the mean, median, standard deviation, and variance of an array of 20 random integers.  
7. Create a 3x4 matrix and find the sum of each row and each column.  
8. Use **boolean indexing** to replace all elements greater than a specific number with that number itself.  
9. Create a 5x5 matrix and set the border elements to 1 and the rest to 0.  
10. Given a 3D array, flatten it to 1D and then reshape it back.


In [13]:
# Create a 4x4 array and extract the diagonal elements
arr=np.arange(0,16).reshape((4,4))
diag=np.diag(arr)
print("Original array :\n",arr)
print("Diagonal elements :\n",diag)

Original array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Diagonal elements :
 [ 0  5 10 15]


In [14]:
# Given a 1D array [1, 2, 3, 4, 5, 6, 7, 8, 9], extract all even numbers.
num=np.arange(1,10)
even=num[num%2==0]
print(even)

[2 4 6 8]


In [15]:
# Replace all odd numbers in an array with -1.
numbers=np.arange(1,10)
replaced_num=np.where(numbers%2==1,-1,numbers)
print("Original array :",numbers)
print("Replaced array :",replaced_num)

Original array : [1 2 3 4 5 6 7 8 9]
Replaced array : [-1  2 -1  4 -1  6 -1  8 -1]


In [16]:
# Normalize a random 3x3 matrix (values scaled between 0 and 1).
mat=np.random.randint(1,100,9).reshape((3,3))
min=np.min(mat)
max=np.max(mat)
normalized_mat=(mat-min)/(max-min)
print("Original matrix :",mat)
print("Normalized matrix :",normalized_mat)

Original matrix : [[97 91 70]
 [44 52 34]
 [68  2 15]]
Normalized matrix : [[1.         0.93684211 0.71578947]
 [0.44210526 0.52631579 0.33684211]
 [0.69473684 0.         0.13684211]]


In [17]:
# Stack two arrays vertically and horizontally using np.vstack() and np.hstack()
arr1=np.random.randint(1,20,6).reshape((2,3))
arr2=np.random.randint(1,20,6).reshape((2,3))
row_stack=np.vstack((arr1,arr2))
col_stack=np.hstack((arr1,arr2))
print("Array 1 :",arr1)
print("Array 2 :",arr2)
print("Row Stack :",row_stack)
print("Column Stack :",col_stack)

Array 1 : [[12  6 12]
 [19 17 14]]
Array 2 : [[10 17 17]
 [12  4 16]]
Row Stack : [[12  6 12]
 [19 17 14]
 [10 17 17]
 [12  4 16]]
Column Stack : [[12  6 12 10 17 17]
 [19 17 14 12  4 16]]


In [18]:
# Compute the mean, median, standard deviation, and variance of an array of 20 random integers.
arr=np.random.randint(1,100,20)
mean=np.mean(arr)
median=np.median(arr)
variance=np.var(arr)
stan_dev=np.std(arr)
print("Array :",arr)
print("Mean :",mean)
print("Median :",median)
print("Standard deviation :",stan_dev)
print("Variance :",variance)


Array : [ 7 13 78 29 61 99  4 97 30 18 40 80 35 92 27 39 13 70 54 28]
Mean : 45.7
Median : 37.0
Standard deviation : 30.209435612073257
Variance : 912.61


In [19]:
# Create a 3x4 matrix and find the sum of each row and each column.
arr=np.arange(1,13).reshape((3,4))
row_sum=np.sum(arr,axis=1)
col_sum=np.sum(arr,axis=0)
print("Matrix :",arr)
print("Row sum :",row_sum)
print("Column sum :",col_sum)

Matrix : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Row sum : [10 26 42]
Column sum : [15 18 21 24]


In [20]:
# Use boolean indexing to replace all elements greater than a specific number with that number itself.
arr=np.random.randint(1,100,10)
print("Original Array :",arr)
num=np.random.randint(1,100)
arr[arr>num]=num
print("After replacement :",arr)


Original Array : [44 77 76 99  2 95 91 32 43  1]
After replacement : [44 77 76 88  2 88 88 32 43  1]


In [21]:
# Create a 5x5 matrix and set the border elements to 1 and the rest to 0.
num=np.zeros((5,5))
num[:,0]=1
num[:,4]=1
num[0,:]=1
num[4,:]=1
print(num)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
# Given a 3D array, flatten it to 1D and then reshape it back.
arr3d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flat_arr=arr3d.flatten()
reshaped=flat_arr.reshape((1,3,4))
print("Original 3d Array :",arr3d)
print("Flattened Array :",flat_arr)
print("Reshaped Array :",reshaped)

Original 3d Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array : [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


## 🔵 Hard Level (Linear Algebra, Broadcasting Tricks, Performance)

1. Create two 3x3 matrices and compute their dot product using `np.dot()` and the `@` operator.  
2. Compute the determinant, rank, and inverse of a random 3x3 matrix.  
3. Solve a linear equation system \( Ax = b \) using `np.linalg.solve`.  
4. Generate a 1D Gaussian distribution array using `np.linspace()` and `np.exp()`.  
5. Create a 10x10 matrix with random values and replace the maximum element with `0`.  
6. Sort a 2D array by its second column.  
7. Generate a 5x5 matrix with random integers and count how many unique values it has.  
8. Compute the pairwise Euclidean distance between two random sets of points (using broadcasting).  
9. Apply a custom function element-wise using `np.vectorize()`.  
10. Benchmark the sum of rows in a 1000x1000 random matrix using both NumPy and Python loops (compare speed).


In [23]:
# Create two 3x3 matrices and compute their dot product using np.dot() and the @ operator
mat1=np.random.randint(1,20,(3,3))
mat2=np.random.randint(1,20,(3,3))
dot_prod1=np.dot(mat1,mat2)
dot_prod2=mat1 @ mat2
print("Matrix 1 :",mat1)
print("Matrix 2 :",mat2)
print("Dot product using np.dot() :",dot_prod1)
print("Dot product using @ :",dot_prod2)



Matrix 1 : [[ 8  9  6]
 [ 7 16  7]
 [ 3  8 10]]
Matrix 2 : [[14 11 16]
 [ 8  2  6]
 [ 1 19 16]]
Dot product using np.dot() : [[190 220 278]
 [233 242 320]
 [116 239 256]]
Dot product using @ : [[190 220 278]
 [233 242 320]
 [116 239 256]]


In [24]:
# Compute the determinant, rank, and inverse of a random 3x3 matrix.
matrix=np.random.randint(1,20,(3,3))
determinant=np.linalg.det(matrix)
rank=np.linalg.matrix_rank(matrix)
inverse=np.linalg.inv(matrix)
print("Original matrix :",matrix)
print("Determinant :",determinant)
print("Rank :",rank)
print("Inverse :",inverse)


Original matrix : [[ 2 17  2]
 [ 9  8  4]
 [10 11 13]]
Determinant : -1150.999999999999
Rank : 3
Inverse : [[-0.05212858  0.17289314 -0.04517811]
 [ 0.06689835 -0.00521286 -0.0086881 ]
 [-0.01650738 -0.12858384  0.11902693]]


In [25]:
# Solve a linear equation system 𝐴𝑥=𝑏 using np.linalg.solve.
A=np.random.randint(1,20,(3,3))
b=np.random.randint(1,20,(3,3))
x=np.linalg.solve(A,b)
print("A :\n",A)
print("\nb :\n",b)
print("\nSolution of Ax=b is:\n",x)

A :
 [[16  5  6]
 [10 17 19]
 [12 10  7]]

b :
 [[ 8  1 15]
 [16  9  2]
 [14 11 15]]

Solution of Ax=b is:
 [[ 0.2742268  -0.07938144  1.15463918]
 [ 1.55876289  2.23298969  1.24742268]
 [-0.69690722 -1.48247423 -1.6185567 ]]


In [26]:
# Generate a 1D Gaussian distribution array using np.linspace() and np.exp().

In [27]:
# Create a 10x10 matrix with random values and replace the maximum element with 0
mat=np.random.randint(1,100,(10,10))
print("Original matrix :",mat)
max=np.max(mat)
print("Maximum element :",max)
mat=np.where(mat==max,0,mat)
print("After replacement :",mat)

Original matrix : [[49 72 95 51  4 18 67 32 32 97]
 [53 96 48 23 49 18 63 32 61 70]
 [98  4 96  9 35 25 20 62 57 23]
 [83  8 14 80 75 43 77 35 86 11]
 [97  4 24 17 53 43 94  5 11 60]
 [61  9 41 91 53 30 93 99 95  2]
 [40  2 81  8 54 13 17 72 46 37]
 [ 5 58 70 54 48 34 66 13 79 72]
 [72 24 58 40 37 53 88 69 44  5]
 [90 95 73 57 89 10 87 23 53 80]]
Maximum element : 99
After replacement : [[49 72 95 51  4 18 67 32 32 97]
 [53 96 48 23 49 18 63 32 61 70]
 [98  4 96  9 35 25 20 62 57 23]
 [83  8 14 80 75 43 77 35 86 11]
 [97  4 24 17 53 43 94  5 11 60]
 [61  9 41 91 53 30 93  0 95  2]
 [40  2 81  8 54 13 17 72 46 37]
 [ 5 58 70 54 48 34 66 13 79 72]
 [72 24 58 40 37 53 88 69 44  5]
 [90 95 73 57 89 10 87 23 53 80]]


In [28]:
# Sort a 2D array by its second column.
arr = np.array([[5, 2, 9],
                [1, 6, 7],
                [3, 4, 8]])

print("Original Array:\n", arr)
sorted_arr=arr[arr[:,1].argsort()]
print("Sorted by 2nd column: ",sorted_arr)

Original Array:
 [[5 2 9]
 [1 6 7]
 [3 4 8]]
Sorted by 2nd column:  [[5 2 9]
 [3 4 8]
 [1 6 7]]


In [29]:
# Generate a 5x5 matrix with random integers and count how many unique values it has. 
matrix=np.random.randint(1,100,(5,5))
unique=np.unique_counts(matrix).values.size
print("Matrix :",matrix)
print("No. of unique elements :",unique)

Matrix : [[82 73 67 92 79]
 [11 82  4 22 40]
 [80 79 76 18 91]
 [21 41 27 30  3]
 [11 21 54 45  6]]
No. of unique elements : 21


In [30]:
# Compute the pairwise Euclidean distance between two random sets of points (using broadcasting).
a=np.array([1,2,3])
b=np.array([4,5,6])
dist=np.sqrt(np.sum((a-b)**2))
print("Array1 :",a)
print("Array2 :",b)
print("Euclidean distance :",dist)

Array1 : [1 2 3]
Array2 : [4 5 6]
Euclidean distance : 5.196152422706632


In [31]:
# Apply a custom function element-wise using np.vectorize().
arr=np.array(["hello","world!","this","is","nump"])
arr2=np.array([1,2,3,4,5,6,7])
vectorization=np.vectorize(str.title)
def add(x):
    return x+5
vectorization2=np.vectorize(add)
print("Array :",vectorization(arr))
print("Array2 :",vectorization2(arr2))

Array : ['Hello' 'World!' 'This' 'Is' 'Nump']
Array2 : [ 6  7  8  9 10 11 12]


In [42]:
# Benchmark the sum of rows in a 1000x1000 random matrix using both NumPy and Python loops (compare speed).
import time
matrix=np.random.randint(1,100,(1000,1000))
sum=np.zeros(1000)
# Using python loops 
start=time.time()
for x in range(0,1000):
    for y in range(0,1000):
        sum[x]+=matrix[x][y]
stop=time.time()-start
print("Time taken using python loop :",stop)

# Using NumPy
start=time.time()
sum=np.sum(matrix,axis=1)
stop=time.time()-start
print("Time taken using numpy :",stop)



Time taken using python loop : 0.46105074882507324
Time taken using numpy : 0.001003265380859375


## 🧠 Bonus Logic Challenges

1. Compute the Fibonacci sequence up to `n = 15` using only NumPy (no loops).  
2. Create a chessboard pattern (8x8 matrix with alternating 0s and 1s).  
3. Find all pairs of elements from two arrays whose sum is divisible by 5.  
4. Rotate a matrix 90° clockwise using slicing.  
5. Simulate rolling two dice 10,000 times and estimate the probability distribution of the sums.


In [ ]:
# Compute the Fibonacci sequence up to n = 15 using only NumPy (no loops)


In [ ]:
# Create a chessboard pattern (8x8 matrix with alternating 0s and 1s)
chess=np.zeros((8,8))
chess[::2,::2]=1
chess[1::2,1::2]=1
print(chess)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
# Find all pairs of elements from two arrays whose sum is divisible by 5.
a=np.array([0,2,2,4,5])
b=np.array([5,7,8,9,10])
c=np.where((a+b)%5==0,(a,b),None)
print(c)

[[0 None 2 None 5]
 [5 None 8 None 10]]


In [ ]:
# Rotate a matrix 90° clockwise using slicing.

In [50]:
# Simulate rolling two dice 10,000 times and estimate the probability distribution of the sums.
dice1=np.random.randint(1,7,10000)
dice2=np.random.randint(1,7,10000)
sum=dice1+dice2
values,counts=np.unique_counts(sum)
prob=counts/10000
for values,prob in zip(values,prob):
    print(f"Sum = {values}   Probability = {prob}")

Sum = 2   Probability = 0.027
Sum = 3   Probability = 0.0522
Sum = 4   Probability = 0.0798
Sum = 5   Probability = 0.1163
Sum = 6   Probability = 0.1424
Sum = 7   Probability = 0.1648
Sum = 8   Probability = 0.1401
Sum = 9   Probability = 0.111
Sum = 10   Probability = 0.0807
Sum = 11   Probability = 0.0552
Sum = 12   Probability = 0.0305


## 📊 Dataset-Based Challenge (Real-World Style Practice)

### 🗂️ Dataset:
| Student_ID | Name    | Math | Physics | Chemistry | Attendance (%) |
|-------------|----------|------|----------|------------|----------------|
| 101         | Aryan    | 78   | 82       | 88         | 92             |
| 102         | Priya    | 85   | 79       | 90         | 96             |
| 103         | Rahul    | 69   | 75       | 70         | 88             |
| 104         | Sneha    | 92   | 95       | 89         | 98             |
| 105         | Kabir    | 76   | 80       | 85         | 90             |

### 🎯 Tasks:
1. Create NumPy arrays for each column of the dataset.  
2. Compute the **average marks** of each student across all subjects.  
3. Find the **highest scorer** in Math and Chemistry.  
4. Compute the **overall class average** for each subject.  
5. Find all students with **attendance > 90%** and **average marks > 80**.  
6. Add a new “Total Marks” column using array operations.  
7. Normalize all marks (scale them between 0 and 1).  
8. Replace all marks below 75 with the average marks of that subject.  
9. Sort students by total marks in descending order.  
10. (Optional) Plot the average marks per student using `matplotlib`.


In [ ]:
# Create NumPy arrays for each column of the dataset.


In [ ]:
# Compute the average marks of each student across all subjects.

In [ ]:
# Find the highest scorer in Math and Chemistry.

In [ ]:
# Compute the overall class average for each subject.

In [ ]:
# Find all students with attendance > 90% and average marks > 80. 

In [ ]:
# Add a new “Total Marks” column using array operations

In [ ]:
# Normalize all marks (scale them between 0 and 1).

In [ ]:
# Replace all marks below 75 with the average marks of that subject.

In [ ]:
# Sort students by total marks in descending order.

In [ ]:
# Plot (optional, if using matplotlib) the average marks per student.