# 🧮 NumPy Practice Set (Easy → Hard + Dataset Challenge)
This notebook is designed to help you master **NumPy** step-by-step — from basic array manipulation to real-world dataset challenges.

**Instructions:**
- Attempt each section in order.
- Write your answers in the provided code cells.
- Use `Shift + Enter` to run cells.
- Don't import any libraries other than `numpy` unless instructed.

Let's get started 🚀

In [2]:
import numpy as np

# Check version
print('NumPy Version:', np.__version__)

NumPy Version: 2.2.6


## 🟢 Easy Level (Basics & Array Manipulation)

1. Create a NumPy array of integers from 1 to 20.  
2. Generate a 3x3 matrix with values ranging from 2 to 10.  
3. Create a 5x5 array of all `True` values.  
4. Convert a Python list `[1, 2, 3, 4, 5]` into a NumPy array and multiply each element by 3.  
5. Create an array of zeros of size 10 and replace the fifth element with 5.  
6. Create an array of 10 random integers between 1 and 100 and find the maximum and minimum values.  
7. Create an array from 0 to 9 and reverse it without using slicing.  
8. Reshape an array of 1 to 9 into a 3x3 matrix.  
9. Create an identity matrix of size 4x4.  
10. Create two arrays and perform element-wise addition, subtraction, multiplication, and division.


In [3]:
# Create a NumPy array of integers from 1 to 20
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
# Generate a 3x3 matrix with values ranging from 2 to 10
matrix=np.arange(2,11).reshape((3,3))
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
# Generate a 5x5 array of all True values
arr2=np.full((5,5),True)
arr2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [11]:
# Convert a Python list [1, 2, 3, 4, 5] into a NumPy array and multiply each element by 3.
L=[1,2,3,4,5]
np_arr=np.array(L)*3
print(np_arr)

[ 3  6  9 12 15]


In [12]:
# Create an array of zeros of size 10 and replace the fifth element with 5.
zeros=np.zeros(10)
zeros[4]=5
print(zeros)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


In [16]:
# Create an array of 10 random integers between 1 and 100 and find the maximum and minimum values.
random_arr=np.random.randint(1,100,10)
max=np.max(random_arr)
min=np.min(random_arr)
print(random_arr)
print("Maximum:",max)
print("Minimum:",min)

[62 60 89 12 10 43  4 36 12 91]
Maximum: 91
Minimum: 4


In [17]:
# Create an array from 0 to 9 and reverse it without using slicing
arr3=np.arange(0,10)
rev_arr=np.flip(arr3)
print("Original Array :",arr3)
print("Reversed Array :",rev_arr)

Original Array : [0 1 2 3 4 5 6 7 8 9]
Reversed Array : [9 8 7 6 5 4 3 2 1 0]


In [19]:
# Reshape an array of 1 to 9 into a 3x3 matrix.
arr4=np.arange(1,10)
reshaped=arr4.reshape((3,3))
print("Reshaped array :\n",reshaped)

Reshaped array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# Create an identity matrix of size 4x4.
identity=np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
# Create two arrays and perform element-wise addition, subtraction, multiplication, and division.
arr1=np.arange(1,6)
arr2=np.arange(6,11)
add_arr=arr1+arr2
sub_arr=arr1-arr2
mult_arr=arr1*arr2
div_arr=arr1/arr2
print("Array 1 :",arr1)
print("Array 2 :",arr2)
print("Addition :\n",add_arr)
print("Subtraction :\n",sub_arr)
print("Multiplication :\n",mult_arr)
print("Division :\n",div_arr)

Array 1 : [1 2 3 4 5]
Array 2 : [ 6  7  8  9 10]
Addition :
 [ 7  9 11 13 15]
Subtraction :
 [-5 -5 -5 -5 -5]
Multiplication :
 [ 6 14 24 36 50]
Division :
 [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


## 🟡 Intermediate Level (Indexing, Math Ops, Broadcasting, Aggregations)

1. Create a 4x4 array and extract the diagonal elements.  
2. Given a 1D array `[1, 2, 3, 4, 5, 6, 7, 8, 9]`, extract all even numbers.  
3. Replace all odd numbers in an array with `-1`.  
4. Normalize a random 3x3 matrix (values scaled between 0 and 1).  
5. Stack two arrays vertically and horizontally using `np.vstack()` and `np.hstack()`.  
6. Compute the mean, median, standard deviation, and variance of an array of 20 random integers.  
7. Create a 3x4 matrix and find the sum of each row and each column.  
8. Use **boolean indexing** to replace all elements greater than a specific number with that number itself.  
9. Create a 5x5 matrix and set the border elements to 1 and the rest to 0.  
10. Given a 3D array, flatten it to 1D and then reshape it back.


In [25]:
# Create a 4x4 array and extract the diagonal elements
arr=np.arange(0,16).reshape((4,4))
diag=np.diag(arr)
print("Original array :\n",arr)
print("Diagonal elements :\n",diag)

Original array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Diagonal elements :
 [ 0  5 10 15]


In [27]:
# Given a 1D array [1, 2, 3, 4, 5, 6, 7, 8, 9], extract all even numbers.
num=np.arange(1,10)
even=num[num%2==0]
print(even)

[2 4 6 8]


In [29]:
# Replace all odd numbers in an array with -1.
numbers=np.arange(1,10)
replaced_num=np.where(numbers%2==1,-1,numbers)
print("Original array :",numbers)
print("Replaced array :",replaced_num)

Original array : [1 2 3 4 5 6 7 8 9]
Replaced array : [-1  2 -1  4 -1  6 -1  8 -1]


In [35]:
# Normalize a random 3x3 matrix (values scaled between 0 and 1).
mat=np.random.randint(1,100,9).reshape((3,3))
min=np.min(mat)
max=np.max(mat)
normalized_mat=(mat-min)/(max-min)
print("Original matrix :",mat)
print("Normalized matrix :",normalized_mat)

Original matrix : [[85 75 35]
 [ 9 73 78]
 [62 54 44]]
Normalized matrix : [[1.         0.86842105 0.34210526]
 [0.         0.84210526 0.90789474]
 [0.69736842 0.59210526 0.46052632]]


In [46]:
# Stack two arrays vertically and horizontally using np.vstack() and np.hstack()
arr1=np.random.randint(1,20,6).reshape((2,3))
arr2=np.random.randint(1,20,6).reshape((2,3))
row_stack=np.vstack((arr1,arr2))
col_stack=np.hstack((arr1,arr2))
print("Array 1 :",arr1)
print("Array 2 :",arr2)
print("Row Stack :",row_stack)
print("Column Stack :",col_stack)

Array 1 : [[16 18 14]
 [15 12 12]]
Array 2 : [[11 12 19]
 [ 2 17  2]]
Row Stack : [[16 18 14]
 [15 12 12]
 [11 12 19]
 [ 2 17  2]]
Column Stack : [[16 18 14 11 12 19]
 [15 12 12  2 17  2]]


In [40]:
# Compute the mean, median, standard deviation, and variance of an array of 20 random integers.
arr=np.random.randint(1,100,20)
mean=np.mean(arr)
median=np.median(arr)
variance=np.var(arr)
stan_dev=np.std(arr)
print("Array :",arr)
print("Mean :",mean)
print("Median :",median)
print("Standard deviation :",stan_dev)
print("Variance :",variance)


Array : [ 3 97 88 12  9  2  1 53 99 55 47 93 41  2  9 88 36  6 97 19]
Mean : 42.85
Median : 38.5
Standard deviation : 37.26563430293385
Variance : 1388.7274999999997


In [42]:
# Create a 3x4 matrix and find the sum of each row and each column.
arr=np.arange(1,13).reshape((3,4))
row_sum=np.sum(arr,axis=1)
col_sum=np.sum(arr,axis=0)
print("Matrix :",arr)
print("Row sum :",row_sum)
print("Column sum :",col_sum)

Matrix : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Row sum : [10 26 42]
Column sum : [15 18 21 24]


In [56]:
# Use boolean indexing to replace all elements greater than a specific number with that number itself.
arr=np.random.randint(1,100,10)
print("Original Array :",arr)
num=np.random.randint(1,100)
arr[arr>num]=num
print("After replacement :",arr)


Original Array : [12 21  5 80 40  2  3 63 68 28]
After replacement : [12 21  5 23 23  2  3 23 23 23]


In [43]:
# Create a 5x5 matrix and set the border elements to 1 and the rest to 0.
num=np.zeros((5,5))
num[:,0]=1
num[:,4]=1
num[0,:]=1
num[4,:]=1
print(num)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
# Given a 3D array, flatten it to 1D and then reshape it back.
arr3d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flat_arr=arr3d.flatten()
reshaped=flat_arr.reshape((1,3,4))
print("Original 3d Array :",arr3d)
print("Flattened Array :",flat_arr)
print("Reshaped Array :",reshaped)

Original 3d Array : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array : [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


## 🔵 Hard Level (Linear Algebra, Broadcasting Tricks, Performance)

1. Create two 3x3 matrices and compute their dot product using `np.dot()` and the `@` operator.  
2. Compute the determinant, rank, and inverse of a random 3x3 matrix.  
3. Solve a linear equation system \( Ax = b \) using `np.linalg.solve`.  
4. Generate a 1D Gaussian distribution array using `np.linspace()` and `np.exp()`.  
5. Create a 10x10 matrix with random values and replace the maximum element with `0`.  
6. Sort a 2D array by its second column.  
7. Generate a 5x5 matrix with random integers and count how many unique values it has.  
8. Compute the pairwise Euclidean distance between two random sets of points (using broadcasting).  
9. Apply a custom function element-wise using `np.vectorize()`.  
10. Benchmark the sum of rows in a 1000x1000 random matrix using both NumPy and Python loops (compare speed).


In [ ]:
# Write your code solutions here 👇


## 🧠 Bonus Logic Challenges

1. Compute the Fibonacci sequence up to `n = 15` using only NumPy (no loops).  
2. Create a chessboard pattern (8x8 matrix with alternating 0s and 1s).  
3. Find all pairs of elements from two arrays whose sum is divisible by 5.  
4. Rotate a matrix 90° clockwise using slicing.  
5. Simulate rolling two dice 10,000 times and estimate the probability distribution of the sums.


In [ ]:
# Write your code solutions here 👇


## 📊 Dataset-Based Challenge (Real-World Style Practice)

### 🗂️ Dataset:
| Student_ID | Name    | Math | Physics | Chemistry | Attendance (%) |
|-------------|----------|------|----------|------------|----------------|
| 101         | Aryan    | 78   | 82       | 88         | 92             |
| 102         | Priya    | 85   | 79       | 90         | 96             |
| 103         | Rahul    | 69   | 75       | 70         | 88             |
| 104         | Sneha    | 92   | 95       | 89         | 98             |
| 105         | Kabir    | 76   | 80       | 85         | 90             |

### 🎯 Tasks:
1. Create NumPy arrays for each column of the dataset.  
2. Compute the **average marks** of each student across all subjects.  
3. Find the **highest scorer** in Math and Chemistry.  
4. Compute the **overall class average** for each subject.  
5. Find all students with **attendance > 90%** and **average marks > 80**.  
6. Add a new “Total Marks” column using array operations.  
7. Normalize all marks (scale them between 0 and 1).  
8. Replace all marks below 75 with the average marks of that subject.  
9. Sort students by total marks in descending order.  
10. (Optional) Plot the average marks per student using `matplotlib`.


In [ ]:
# Write your dataset manipulation code here 👇
